// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://targfsmbvkysgitsdacw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcmdmc21idmt5c2dpdHNkYWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTU3MjMsImV4cCI6MjA2NDUzMTcyM30.p-U7AiOY4li0xyGMfbbLudF7svi1ItRbRxTm8BDtQYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);